/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Luis Sepulveda
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public Principal() {
        initComponents();
    }

    public JButton getCarrito() {
        return Carrito;
    }

    public void setCarrito(JButton Carrito) {
        this.Carrito = Carrito;
    }

    public JDesktopPane getEscritorio() {
        return Escritorio;
    }

    public void setEscritorio(JDesktopPane Escritorio) {
        this.Escritorio = Escritorio;
    }

    public JButton getIngreso() {
        return Ingreso;
    }

    public void setIngreso(JButton Ingreso) {
        this.Ingreso = Ingreso;
    }

    public JButton getPedidos() {
        return Pedidos;
    }

    public void setPedidos(JButton Pedidos) {
        this.Pedidos = Pedidos;
    }

    public JButton getProductos() {
        return Productos;
    }

    public void setProductos(JButton Productos) {
        this.Productos = Productos;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }    

    public JButton getCerrar() {
        return Cerrar;
    }

    public void setCerrar(JButton Cerrar) {
        this.Cerrar = Cerrar;
    }

    public JLabel getLblCerrar() {
        return lblCerrar;
    }

    public void setLblCerrar(JLabel lblCerrar) {
        this.lblCerrar = lblCerrar;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Ingreso = new javax.swing.JButton();
        Productos = new javax.swing.JButton();
        Carrito = new javax.swing.JButton();
        Pedidos = new javax.swing.JButton();
        Cerrar = new javax.swing.JButton();
        lblCerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(350, 330));
        setMinimumSize(new java.awt.Dimension(350, 330));
        setPreferredSize(new java.awt.Dimension(350, 330));
        getContentPane().setLayout(null);

        Escritorio.setBackground(new java.awt.Color(255, 255, 255));
        Escritorio.setMaximumSize(new java.awt.Dimension(360, 330));
        Escritorio.setMinimumSize(new java.awt.Dimension(360, 330));

        jPanel1.setBackground(new java.awt.Color(71, 168, 244));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gestor Pedidos");
        jPanel1.add(jLabel3);

        Escritorio.add(jPanel1);
        jPanel1.setBounds(0, 20, 360, 50);

        Ingreso.setBackground(new java.awt.Color(71, 168, 244));
        Ingreso.setFont(new java.awt.Font("Trebuchet MS", 0, 22)); // NOI18N
        Ingreso.setForeground(new java.awt.Color(255, 255, 255));
        Ingreso.setText("Registro/Ingreso");
        Ingreso.setAutoscrolls(true);
        Ingreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoActionPerformed(evt);
            }
        });
        Escritorio.add(Ingreso);
        Ingreso.setBounds(20, 80, 300, 40);

        Productos.setBackground(new java.awt.Color(71, 168, 244));
        Productos.setFont(new java.awt.Font("Trebuchet MS", 0, 22)); // NOI18N
        Productos.setForeground(new java.awt.Color(255, 255, 255));
        Productos.setBorder(null);
        Productos.setText("Productos");
        Productos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Productos.setFocusPainted(false);
        Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosActionPerformed(evt);
            }
        });
        Escritorio.add(Productos);
        Productos.setBounds(20, 130, 300, 40);

        Carrito.setBackground(new java.awt.Color(71, 168, 244));
        Carrito.setFont(new java.awt.Font("Trebuchet MS", 0, 22)); // NOI18N
        Carrito.setForeground(new java.awt.Color(255, 255, 255));
        Carrito.setText("Carrito");
        Carrito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Carrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarritoActionPerformed(evt);
            }
        });
        Escritorio.add(Carrito);
        Carrito.setBounds(20, 180, 300, 40);

        Pedidos.setBackground(new java.awt.Color(71, 168, 244));
        Pedidos.setFont(new java.awt.Font("Trebuchet MS", 0, 22)); // NOI18N
        Pedidos.setForeground(new java.awt.Color(255, 255, 255));
        Pedidos.setText("Pedidos");
        Pedidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Pedidos.setMaximumSize(new java.awt.Dimension(167, 29));
        Pedidos.setMinimumSize(new java.awt.Dimension(167, 29));
        Pedidos.setPreferredSize(new java.awt.Dimension(167, 29));
        Pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidosActionPerformed(evt);
            }
        });
        Escritorio.add(Pedidos);
        Pedidos.setBounds(20, 230, 300, 40);

        Cerrar.setBackground(new java.awt.Color(255, 255, 255));
        Cerrar.setBorder(null);
        Cerrar.setBorderPainted(false);
        Cerrar.setOpaque(false);
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        Escritorio.add(Cerrar);
        Cerrar.setBounds(250, 0, 80, 20);
        Escritorio.add(lblCerrar);
        lblCerrar.setBounds(250, 0, 80, 20);

        getContentPane().add(Escritorio);
        Escritorio.setBounds(0, 0, 350, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidosActionPerformed
    }//GEN-LAST:event_PedidosActionPerformed

    private void ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosActionPerformed
    }//GEN-LAST:event_ProductosActionPerformed

    private void CarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarritoActionPerformed
    }//GEN-LAST:event_CarritoActionPerformed

    private void IngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoActionPerformed
    }//GEN-LAST:event_IngresoActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new Principal().setVisible(true);
                }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Carrito;
    private javax.swing.JButton Cerrar;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JButton Ingreso;
    private javax.swing.JButton Pedidos;
    private javax.swing.JButton Productos;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCerrar;
    // End of variables declaration//GEN-END:variables
}
